- name: 'instalando as dependencias do sistema'
  apt:
    update_cache: yes
    name:
      - php7.4
      - apache2
      - libapache2-mod-php7.4
      - php7.4-gd
      - php7.4-mysql
    state: latest
  become: yes
- name: 'Baixar a o arquivo de instalacao do wordpress'
  get_url:
    url: https://wordpress.org/wordpress-6.0.2.tar.gz
    dest: '/tmp/wordpress.tar.gz'
- name: 'Descompactar o arquivo do WordPress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Copiar configuracao do WordPress'
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configurar o wp-config com dados do banco de dados'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
    backup: yes
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_username }}"}
    - { regex: 'password_here', value:  "{{ wp_password }}"}
    - { regex: 'localhost', value: "{{ db_host_address }}" }
  become: yes

- name: 'Copiando configuracao do Apache 2 para servir o WordPress'
  copy:
    src: 'files/000-default.conf'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache