$script_mysql = <<-'SCRIPT'
	apt update &&  \
	apt install -y mysql-server-5.7 && \
	mysql -e "CREATE USER 'phpuser'@'%' IDENTIFIED BY 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider "virtualbox" do |v|
  	v.memory = 512
  	v.cpus = 1
  end
  
#  config.vm.define "mysqldb" do |mysql|
#    mysql.vm.network "public_network", ip: "192.168.1.15"
#    mysql.vm.provision "shell", inline: "cat /config/id_bionic.pub >> .ssh/authorized_keys"
#    mysql.vm.provision "shell", inline: $script_mysql
#    mysql.vm.provision "shell", inline: "cat /config/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
#    mysql.vm.provision "shell", inline: "service mysql restart"
#    mysql.vm.synced_folder "./config", "/config"
#    mysql.vm.synced_folder ".", "/vagrant", disabled: true
#  end

  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.provider "virtualbox" do |vb|
  		vb.memory = 1024
  		vb.cpus = 2
  		vb.name = "phpweb_bionic_machine"
  	end
  	
    phpweb.vm.network "forwarded_port", guest: 80, host: 8088
    phpweb.vm.network "public_network", ip: "192.168.1.17"
    phpweb.vm.provision "shell", inline: "apt update && apt install puppet -y"
    phpweb.vm.provision "puppet" do |puppet|
    	puppet.manifests_path = "./config/manifests"
	    puppet.manifest_file = "phpweb.pp"
  	end
  end
  
  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network", ip: "192.168.1.18"
    mysqlserver.vm.provision "shell", inline: "cat /vagrant/.ssh/id_bionic.pub >> .ssh/authorized_keys"
  end
  
  config.vm.define "mencached" do |mencached|
	mencached.vm.box = "centos/7"
	mencached.vm.provider "virtualbox" do |vb|
		vb.memory = 512
		vb.cpus = 1
		vb.name = "centos7_memcached"
    end
  end
 end
