$script_mysql = <<-'SCRIPT'
	apt update &&  \
	apt install -y mysql-server-5.7 && \
	mysql -e "CREATE USER 'phpuser'@'%' IDENTIFIED BY 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "mysqldb" do |mysql|
    mysql.vm.network "public_network", ip: "192.168.1.15"
    mysql.vm.provision "shell", inline: "cat /config/id_bionic.pub >> .ssh/authorized_keys"
    mysql.vm.provision "shell", inline: $script_mysql
    mysql.vm.provision "shell", inline: "cat /config/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    mysql.vm.provision "shell", inline: "service mysql restart"
    mysql.vm.synced_folder "./config", "/config"
    mysql.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.network "forwarded_port", guest: 80, host: 8088
    phpweb.vm.network "public_network", ip: "192.168.1.17"
    phpweb.vm.provision "shell", inline: "apt update && apt install puppet -y"
    phpweb.vm.provision "puppet" do |puppet|
    	puppet.manifests_path = "./config/manifests"
	    puppet.manifest_file = "phpweb.pp"
  	end
  end
  
  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network", ip: "192.168.1.18"
    mysqlserver.vm.provision "shell", inline: "cat /vagrant/.ssh/id_bionic.pub >> .ssh/authorized_keys"
  end
  
  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.1.19"
  	ansible.vm.provision "shell",
            inline: "apt-get update && \
                     apt-get install -y software-properties-common && \
                     apt-add-repository --yes --update ppa:ansible/ansible && \
                     apt-get install -y ansible"
     ansible.vm.provision "shell",
        inline: "cp /vagrant/config/id_bionic  /home/vagrant && \
                chmod 600 /home/vagrant/id_bionic && \
                chown vagrant:vagrant /home/vagrant/id_bionic"
	 ansible.vm.provision "shell",
        inline: "ansible-playbook -i /vagrant/config/ansible/hosts /vagrant/config/ansible/playbook.yml"
  end
 end
