---
- hosts: database
  handlers:
    - name: restart mariadb 
      service: 
        name: mariadb
        state: restarted
      become: yes
  vars:
    mariadb_root_password: "root"
  tasks:
      - name: 'instalando as dependencias do sistema'
        apt:
          update_cache: yes
          name:
            - mariadb-server
            - mariadb-client
            - python3-mysqldb
          state: latest
        become: yes
      - name: 'Adicionar senha root'
        mysql_user:
          login_user: root
          login_password: "{{ mariadb_root_password }}"
          user: root
          check_implicit_admin: true
          password: "{{ mariadb_root_password }}"
          host: localhost
        become: yes
      - name: 'Criar o banco de dados no MySQL'
        mysql_db:
          name: wordpress_db
          login_user: root
          login_password: root
          state: present
      - name: 'Criar usuario no MySQL para WordPress'
        mysql_user:
          login_user: root
          login_password: root
          name: wordpress_user
          password: 123456
          priv: 'wordpress_db.*:ALL'
          host: "{{ item }}"
          state: present
        with_items:
            - 'localhost'
            - '127.0.0.1'
            - '192.168.56.8'
      - name: 'Configurar o acesso remoto para o MariaDB'
        copy:
          src: 'files/50-server.cnf'
          dest: '/etc/mysql/mariadb.conf.d/50-server.cnf'
        become: yes
        notify:
          - restart mariadb

- hosts: wordpress
  handlers:
    - name: restart apache 
      service: 
        name: apache2
        state: restarted
      become: yes
  tasks:
    - name: 'instalando as dependencias do sistema'
      apt:
        update_cache: yes
        name:
          - php7.4
          - apache2
          - libapache2-mod-php7.4
          - php7.4-gd
          - php7.4-mysql
        state: latest
      become: yes
    - name: 'Baixar a o arquivo de instalacao do wordpress'
      get_url:
        url: https://wordpress.org/wordpress-6.0.2.tar.gz
        dest: '/tmp/wordpress.tar.gz'
    - name: 'Descompactar o arquivo do WordPress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: 'Copiar configuracao do WordPress'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configurar o wp-config com dados do banco de dados'
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '123456'}
        - { regex: 'localhost', value: '192.168.56.9' }
      become: yes
    
    - name: 'Copiando configuracao do Apache 2 para servir o WordPress'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache