- hosts: all
  tasks:
    - name: 'instalando as dependencias do sistema'
      apt:
        name:
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - php5-mcrypt
          - mysql-server-5.6
          - python-mysqldb
          - php5-mysql
        state: latest
      become: yes
    - name: 'Criar o banco de dados no MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present  # para remover use absent, para vfazer dump use dump
    - name: 'Criar usuario no MySQL'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 123456
        priv: 'wordpress_db.*:ALL'
        state: present