- hosts: all
  tasks:
    - name: 'instalando as dependencias do sistema'
      apt:
        name:
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - php5-mcrypt
          - mysql-server-5.6
          - python-mysqldb
          - php5-mysql
        state: latest
      become: yes

    - name: 'Criar o banco de dados no MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present  # para remover use absent, para vfazer dump use dump

    - name: 'Criar usuario no MySQL'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 123456
        priv: 'wordpress_db.*:ALL'
        state: present
    - name: 'Baixar a o arquivo de instalacao do wordpress'
      get_url:
        url: https://wordpress.org/wordpress-6.0.2.tar.gz
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Descompactar o arquivo do WordPress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes
    
    - name: 'Copiar configuracao do WordPress'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configurar o wp-config com dados do banco de dados'
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '123456'}
      become: yes