Vagrant.configure("2") do |config|

  config.vm.define "wordpress" do |wp|
    wp.vm.box = "debian/bullseye64"
    wp.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "wordpress_com_php"
    end
    wp.vm.network "private_network", ip: "192.168.56.8"
  end

  config.vm.define "database" do |db|
    db.vm.box = "debian/bullseye64"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "database_mysql"
    end
    db.vm.network "private_network", ip: "192.168.56.9"
  end
end