Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
#  config.vm.box_check_update = false
#  config.vm.network "forwarded_port", guest: 80, host: 8080
#  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "192.168.1.8"
  config.vm.network "private_network", ip: "192.168.56.8"
  config.vm.network "public_network", ip: "192.168.56.8"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
  config.vm.provision "shell", inline: "cat /vagrant/.ssh/wordpress.pub .ssh/authorized_keys"
end
